[김동규] 초기 모델링
wecode-bootcamp-korea/30-2nd-clnass505-backend pull request #1
Opened 2022-03-15 08:56 UTC by pasitoapasito

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- core/users/lectures/reviews app models.py 생성

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
 - ERD를 바탕으로 각 앱에 필요한 models.py 작성

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- models.py의 Charfield에서 blank=True 옵선과 Null=True 옵션의 차이점에 대해 알게되었습니다.

<br />

2022-03-15 11:16 UTC, Kang-kyunghun requested changes

2022-03-15 11:16 UTC, Kang-kyunghun commented on lectures/models.py
> +    image_url = models.CharField(max_length=200)
url 200 너무 짧습니다. 2000으로 바꿔주세요.

2022-03-15 11:16 UTC, Kang-kyunghun commented on reviews/models.py
> +    image_url = models.CharField(max_length=200)
여기도 길이가 짧습니다.

2022-03-15 11:16 UTC, Kang-kyunghun commented on users/models.py
> +    lecture = models.ForeignKey('lectures.Lecture', on_delete=models.CASCADE)
many to many field를 활용해 보면 좋을 것 같습니다.
나중에 user 입장에서 수강중인 데이터 가져올 때 편할 것 같네요.

2022-03-15 11:16 UTC, Kang-kyunghun commented on users/models.py
> +    lecture = models.ForeignKey('lectures.Lecture', on_delete=models.CASCADE)
Like field도 마찬가지로 many to many를 활용해보면 좋을 것 같아요.

2022-03-16 01:10 UTC, Kang-kyunghun commented
- ManyToManyField을 user와 lecture 둘 다 선언한 이유를 남겨주세요.
- like 관련 ManyToManyField은 사용 안 하기로 한 건가요?

2022-03-16 01:19 UTC, pasitoapasito commented
user와 lecture 사이에 중간 테이블로 likes와 users_lectures가 존재하는데 경훈님 리뷰 주신대로 두 테이블 모두 중간테이블로 사용하여 manytomany field를 만들었습니다. user 클래스 한쪽에 모두 manytomany 필드를 만들 수 없어서 user 클래스와 lecture 클래스에 한개씩 만들었는데 혹시 경훈님의 리뷰 의도를 저희가 잘 못 이해한 걸까요..?

2022-03-16 02:02 UTC, Kang-kyunghun commented
LGTM!

2022-03-16 02:02 UTC, merged