[김동규] 소셜 로그인 & 로그인 데코레이터 기능 구현 및 소셜 로그인 테스트 코드 작성
wecode-bootcamp-korea/30-2nd-clnass505-backend pull request #3
Opened 2022-03-16 09:22 UTC by pasitoapasito

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [x] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 소셜 로그인 기능과 로그인 데코레이터 기능 구현
- 소셜 로그인 테스트 코드 작성(성공/실패)

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 프론트엔드에서 카카오톡 인증토큰을 받아온 후, 카카오 유저 정보를 추출하여 데이터베이스에 저장한다.
2. 데이터베이스에 저장된 유저정보를 바탕으로 우리 서비스의 자체 토큰을 발행한다.
3. 발행한 자체 토큰을 json 객체 형태로 프론트엔드에 전달한다.
4. 이후 로그인이 필요한 기능을 위해 앞서 발급한 토큰을 인증/인가하는 로그인 데코레이터 기능을 구현함
5. 소셜 로그인의 테스트 코드를 작성함(user create, user get, invaild-token, keyerror case)

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 소셜 로그인의 전체 flow에 대한 전반적인 이해를 했습니다.
- 소셜 로그인에서 프론트엔드와 백엔드의 역할에 대해 명확히 이해했습니다.
- 좋은 개발을 위한 테스트 코드의 필요성에 대해 알게 되었습니다.

<br />

## :: 기타 질문 및 특이 사항
- 소셜 로그인 단계에서 카카오로부터 받은 인증코드를 백엔드에서 처리할 경우 정확히 어떤 에러에 직면하는지 궁금합니다!!

2022-03-17 01:43 UTC, Kang-kyunghun requested changes

2022-03-17 01:43 UTC, Kang-kyunghun commented on core/decorator.py
> +from users.models       import User
너무 많은 공백을 주셨습니다.

```suggestion
from django.conf  import settings
from django.http  import JsonResponse

from users.models import User
```

2022-03-17 01:43 UTC, Kang-kyunghun commented on core/decorator.py
> +
공백 한 줄 제거 해주세요.

2022-03-17 01:43 UTC, Kang-kyunghun commented on users/views.py
> +from users.models import User
datetime은 built in package이므로 맨 윗단에서 선언해 주세요.
```suggestion
from datetime     import datetime, timedelta

from django.views import View
from django.http  import JsonResponse
from django.conf  import settings

from users.models import User
```

2022-03-17 01:43 UTC, Kang-kyunghun commented on users/views.py
> +            response    = requests.get('https://kapi.kakao.com/v2/user/me', headers=headers, timeout=3)
- requests 모듈을 사용하실 때에는 timeout 옵션을 반드시 설정해주셔야 합니다. 그 이유는 timeout option을 추가하지 않으면 서버의 응답을 계속해서 기다리고 있는 문제가 발생 합니다.  timeout 옵션을 추가해 주세요.
- response로 에러가 왔을 때에 대한 예외처리도 추가해 주세요.

2022-03-17 01:43 UTC, Kang-kyunghun commented on users/views.py
> +            )
- get_or_create의 2번째 return 값은 boolean이기 때문에 변수 앞에 is_을 붙여주는 것이 좋습니다.
- get_or_create을 사용할 때는 pk 값으로 사용 되는 값으로만 객체를 특정 지어주어야 합니다. 그렇지 않으면 조건을 모두 만족하는 객체를 찾기 때문에 값이 조그만 달라도 새로운 객체를 만들어 버립니다.

```suggestion
            user, is_created = User.objects.get_or_create(
                kakao_id  = kakao_id,
            )
```

2022-03-17 04:18 UTC, pasitoapasito commented on core/decorator.py
> +
넵 수정하겠습니다!!

2022-03-17 04:21 UTC, pasitoapasito commented on users/views.py
> +            response    = requests.get('https://kapi.kakao.com/v2/user/me', headers=headers, timeout=3)
넵 예외처리 추가하겠습니다!!
혹시 timeout 옵션이 위의 코드에서 get() 함수의 세번째 인자인 timeout=3과는 다른 건가요..?

2022-03-17 04:21 UTC, pasitoapasito commented on users/views.py
> +            )
넵 리뷰 반영해서 코드 수정하겠습니다!!

2022-03-17 04:54 UTC, Kang-kyunghun commented on users/views.py
> +            response    = requests.get('https://kapi.kakao.com/v2/user/me', headers=headers, timeout=3)
오호!! 맞습니다. 
제가 놓쳤네요. 잘 하셨습니다.

2022-03-17 04:59 UTC, Kang-kyunghun commented
소스코드는 괜찮은 것 같습니다.
Unit test 추가되면 이어서 리뷰 진행 하겠습니다.

2022-03-18 02:33 UTC, Kang-kyunghun commented
고생하셨습니다.!!
LGTM~!

2022-03-18 02:34 UTC, merged