[김동규] LectureDetail API 기능 구현
wecode-bootcamp-korea/30-2nd-clnass505-backend pull request #4
Opened 2022-03-18 13:36 UTC by pasitoapasito

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- Lecture의 상세 정보를 제공하는 API 기능 구현 및 포스트맨 테스트 완료

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
- 프론트엔드에서 path parameter로 lecture_id를 받으면 해당 lecture 상세 정보를 보내주는 API 기능 구현

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- select_related() 함수와 prefetch_related() 함수 활용(ORM 최적화 세션에서 배운 내용 적용)

<br />

2022-03-19 14:33 UTC, Kang-kyunghun requested changes

2022-03-19 14:33 UTC, Kang-kyunghun commented on lectures/tests.py
> +from reviews.models  import *
* 사용하지 말고 필요한 객체만 불러와 주세요.

2022-03-19 14:33 UTC, Kang-kyunghun commented on lectures/tests.py
> +    def setUp(self):
**setUp()**
`TestCase`를 상속받은 경우, `setUp()`은 각각의 `test_method`가 실행될 때마다 실행됩니다. 
그렇기 때문에 테스트 중에 내용이 변경될 수 있는 객체를 생성할 수 있습니다.
ex)
```python
    def setUp(self):
        user = User.objects.create(name="a")

    def test_xxxx(self):
        user.name = "b"
        user.save()
        ....
```
이런 경우가 아니라면, 즉 test 전체에서 사용되는 수정되거나 변경되지 않을 객체들을 생성하는 경우에 `setUp`에서 객체를 생성하게 되면 매번 객체를 생성하게 되므로 느려집니다.

**setUpTestData()**
테스트에서 읽기 전용 데이터로만 사용하는 객체의 경우 class method인 `setUpTestData`를 사용하면 한번만 생성할 수 있게 되므로 테스트 처리 속도가 빨라집니다.
가급적이면 `setUp`에서 매번 객체를 생성하는 것을 지양하는 것이 좋습니다.

2022-03-19 14:33 UTC, Kang-kyunghun commented on lectures/views.py
> +                    prefetch_related('lectureimage_set', 'review_set', 'like_set')[0]
filter가 아닌 get으로 불어와 주세요. 이에 대한 예외처리도 추가해 주세요.

2022-03-19 14:33 UTC, Kang-kyunghun commented on lectures/views.py
> +            return JsonResponse({'message' : 'LECTURE_NOT_EXIST'}, status=400)
select_related와 prefetch_related를 사용해서 query가 많이 줄었나요?? 
적용 전 query 수와 적용 후의 query 수를 비교할 수 있는 사진을 첨부해 주세요.

2022-03-21 00:08 UTC, pasitoapasito commented on lectures/tests.py
> +from reviews.models  import *
넵 수정하겠습니다!!

2022-03-21 00:09 UTC, pasitoapasito commented on lectures/views.py
> +                    prefetch_related('lectureimage_set', 'review_set', 'like_set')[0]
넵 수정하겠습니다!!

2022-03-21 00:09 UTC, pasitoapasito commented on lectures/views.py
> +                    prefetch_related('lectureimage_set', 'review_set', 'like_set')[0]
혹시 filter() 함수가 아닌 get() 함수를 사용해야만 하는 이유가 있을까요..?

2022-03-21 00:10 UTC, pasitoapasito commented on lectures/views.py
> +            return JsonResponse({'message' : 'LECTURE_NOT_EXIST'}, status=400)
테스트 후 비교사진 첨부하겠습니다!!

2022-03-21 00:10 UTC, pasitoapasito commented on lectures/tests.py
> +    def setUp(self):
넵 설명해주신 부분 이해하고 적용해보겠습니다!!

2022-03-21 00:52 UTC, pasitoapasito commented on lectures/views.py
> +            return JsonResponse({'message' : 'LECTURE_NOT_EXIST'}, status=400)
<img width="1266" alt="select_related()   prefetch_related() 사용 결과" src="https://user-images.githubusercontent.com/89829943/159193335-411b24bd-c1ad-4bcd-9d5c-5163fc027f70.png">
<img width="1258" alt="select_related()   prefetch_related() 사용X 결과" src="https://user-images.githubusercontent.com/89829943/159193344-1bb5d947-bfd2-43b6-856c-f0083332b9a4.png">

select_related() 함수와 prefetch_related() 함수를 사용했을 때와 사용하지 않았을 때의 비교 사진 첨부해서 올렸습니다!!
해당 함수들을 사용했을 때 쿼리 숫자가 3개 더 적었습니다!! 실제로 쿼리 숫자가 눈에 띄게 많이 줄지는 않는 것 같습니다!!

2022-03-22 09:35 UTC, Kang-kyunghun commented
LGTM~~!

2022-03-22 09:35 UTC, merged