Feature/lecture upload
wecode-bootcamp-korea/30-2nd-clnass505-backend pull request #5
Opened 2022-03-19 09:13 UTC by 97woo

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
강의생성api를 aws s3를 사용하여 구현합니다. 

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 강의생성시 form-data로  사진을 받아서 s3에 업로드하고 이미지url만 db에 저장합니다.
2. 강의생성시에 강의테이블 생성, 강의이미지 테이블 생성, 유저테이블 수정 됩니다.
3. 다섯장의 사진이 원하는 s3 폴더 각각 저장이 되고 이름은 uuid를 사용하여 난수처리하였습니다.

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
aws-s3를 사용하여 이미지를 업로드해볼수 있엇습니다.
초기 셋팅과 사용법이 어려웠지만 좋은 경험이였던것 같습니다.
<br />

## :: 기타 질문 및 특이 사항
- 코드에 중복된 부분을 정리하고싶은데 아무리 쳐다봐도 정리하는 방법을 알 수 없어서 ... 힌트를 부탁드립니다.

2022-03-19 14:28 UTC, Kang-kyunghun requested changes

2022-03-19 14:28 UTC, Kang-kyunghun commented on lectures/views.py
> +class FileView(View):
```suggestion
class LecturesView(View):
```
수업과 관련된 view이기 때문에 다음과 같이 이름을 변경하는 것이 좋을 것 같습니다.

2022-03-19 14:28 UTC, Kang-kyunghun commented on lectures/views.py
> +    @signin_decorator
```suggestion
    )
    
    @signin_decorator
```

2022-03-19 14:28 UTC, Kang-kyunghun commented on lectures/views.py
> +            profile_urls = f"{BUCKET_ADDRESS}/{profile_url}"
```suggestion
            BUCKET_ADDRESS    = 'https://woosbucket.s3.ap-northeast-2.amazonaws.com'
            BUCKET_THUMNAIL  = 'thumnail'
            BUCKET_IMAGE = 'image'
            BUCKET_PROFILE = 'profile'
            
            profile  = request.FILES['profile']
            user     = request.user
           
            url          = f"{BUCKET_DIRECTORY}/{str(uuid4())}"
            urls         = f"{BUCKET_ADDRESS}/{url}"
            profile_url  = f"{BUCKET_DIRECTORY3}/{str(uuid4())}"
            profile_urls = f"{BUCKET_ADDRESS}/{profile_url}"
```
1. BUCKET_DIRECTORY1,2 가 아닌 명확하게 변수명을 지정하는 것이 좋습니다.
2. BUCKET 관련 변수는 my_settings.py에 옮기는 것도 좋습니다.
3. user를 이미 알고 있는데, users를 가져올 이유가 없을 것 같습니다.
4. url과 urls, profile_url과 profile_urls가 각 각 무엇을 의미하는지 파악이 잘 안 됩니다. 불필요하게 나줘서 변수를 만든 것 같습니다.

2022-03-19 14:28 UTC, Kang-kyunghun commented on lectures/views.py
> +            )
이 부분 때문에 users을 다시 가져온 것 같은데, save()을 이용해서 users 없이 user 로만 구현해 보세요.

2022-03-19 14:28 UTC, Kang-kyunghun commented on lectures/views.py
> +            for i in range(3):
range가 아닌 입력 받은 이미지 수 만큼 for문이 돌아가게 해야 됩니다. 지금은 이미지를 3개만 받기로 했다고 했지만, 언제든지 기획은 바뀔 수 있기 때문입니다.

2022-03-19 14:28 UTC, Kang-kyunghun commented on lectures/views.py
> +            return JsonResponse({"message" : "KEY_ERROR"},status=400)
한 api에서 많은 테이블들을 생성하고 있습니다. 이럴 때는 transaction을 사용해야 합니다. django에서 어떻게 transaction을 사용하는지 찾아보고 적용해 보세요.

2022-03-19 14:28 UTC, Kang-kyunghun commented
전체적인 논리나 흐름은 괜찮아 보입니다. 
일단은 제가 리뷰 드린 사항 위주로 수정 하신 뒤에 다음주 라이브 코드 리뷰 때 조금 더 자세히 리뷰 진행하겠습니다.

2022-03-22 04:00 UTC, Kang-kyunghun requested changes

2022-03-22 04:00 UTC, Kang-kyunghun commented on lectures/views.py
> +                user.description       = request.POST['introduce']
여기도 keyerror가 날 수 있는 부분이네요.
위로 올려주세요.

2022-03-22 04:00 UTC, Kang-kyunghun commented on lectures/views.py
> +        except KeyError:
except transaction.TransactionManagementError:
            return JsonResponse({'message':'TransactionManagementError'}, status=400)
해당 예외처리 추가하면 좋을 것 같습니다.

2022-03-22 04:03 UTC, 97woo commented on lectures/views.py
> +                user.description       = request.POST['introduce']
수정하겠습니다

2022-03-22 04:03 UTC, 97woo commented on lectures/views.py
> +        except KeyError:
추가하였습니다 감사합니다!

2022-03-23 09:38 UTC, Kang-kyunghun requested changes

2022-03-23 09:38 UTC, Kang-kyunghun commented on lectures/urls.py
> +>>>>>>> 9bbe5da (modified:lectureupload.api)
여기 한 번만 확인해 주세요.

2022-03-23 09:38 UTC, Kang-kyunghun commented on lectures/urls.py
> +<<<<<<< HEAD
여기도 확인

2022-03-23 09:38 UTC, Kang-kyunghun commented on clnass505/settings.py
> +    'storages'
storage는 app이 아니지 않나요??

2022-03-23 09:48 UTC, 97woo commented on clnass505/settings.py
> +    'storages'
수정하였습니다. 감사합니다

2022-03-24 00:23 UTC, Kang-kyunghun requested changes

2022-03-24 00:23 UTC, Kang-kyunghun commented on lectures/urls.py
> +    path('/upload',LecturesView.as_view()),
REST에 맞게 동사는 http method만 표시합니다. 따라서 수업을 등록하는 기능이기 때문에 아래와 같이 수정하면 좋을 것 같습니다.
즉, 지원님의 lecture list와 건우님의 lecture 등록이 같은 view안에 get과 post로 같이 존재해야 되어야 합니다.
이 부분을 두분이서 View이름과 url을 통일해 주세요.

```suggestion
    path('',LecturesView.as_view()),
```

2022-03-24 05:32 UTC, Kang-kyunghun commented
LGTM~!!

2022-03-24 05:32 UTC, merged